### ISSUE TITLE
Tool does not factor in low stock of Materials

### ISSUE THREAD

**Issue by thierrywall** [znibb/WowProfessionLevelingTool#6]
Some Materials are scarce on some servers, and the AH does not have enough of them to complete the steps outline.
One examples is Moss Agate used by engineering.
On Stalagg (Horde) there are only a handful available, and it's being suggested I need 25.

Having the tool Check stock levels or give the ability to exclude some materials manually, so it can calculate alternatives would be great.

**Comment by znibb** [comment]
Sorry for the late reply.

The main reason why I haven't bothered with adding this is the delay in Nexushub updates. The market price stays reasonably stable but the quantity available is volatile enough that it wouldn't really make sense. You make a perfectly valid point but without real-time (or close to) data it's not technically feasible in my mind.
